version: "3"
services:
  ntp:
    container_name: ntp
    image: dockurr/chrony:latest
    ports:
      - 123:123/udp
    environment:
      - NTP_SERVERS=time.cloudflare.com
      - LOG_LEVEL=0
#      - TZ=America/Vancouver
#      - NOCLIENTLOG=true
#      - ENABLE_NTS=true
#      - ENABLE_SYSCLK=true
    restart: always
